# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20171225_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=b'image/'),
        ),
    ]
