# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20180105_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
