# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_topic_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Curso',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(blank=True, to='App.User'),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
