# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20180107_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='neg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='neu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
